### ISSUE TITLE
Support Rollbar v4

### ISSUE THREAD

**Issue by Chris53897** [rollbar/rollbar-php-symfony-bundle#85]
@danielmorell 
I will try to help a bit with a version to support v4.
Can you suggest a best way to do this?
A new major version 6 of this bundle as a new brach from `master` ?

**Comment by danielmorell** [comment]
I appreciate your willingness to help! I think since we released v5 of this project with only support for PHP 8.0 and above we should be able to add support for Rollbar PHP v4 in addition to v3. I feel like this could be done without any breaking changes.

If this is possible, we should be able to release it as v5.1.
